blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blogapp.urls', namespace='blog'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name="index"),
    # path('posts/', views.PostListView.as_view(), name='post_list'),
    path('posts/', views.post_list, name='post_list'),
    path('posts/<str:category>', views.post_list, name='post_list_category'),
    path('posts/detail/<id>', views.posts_details, name='posts_detail'),
    path('ticket', views.ticket, name='ticket'),
    path('posts/<post_id>/comment', views.post_comment, name="post_comment"),
    # path('create_post',views.create_posts_view,name = "create__posts"),
    path('search', views.post_search, name="post_search"),
    path('profile', views.profile, name="profile"),
    path('profile/create_post', views.create_post, name="create_post"),
    path('profile/create_post/<post_id>', views.edit_post, name="edit_post"),
    path('profile/delete_post/<post_id>', views.delete_post, name="delete_post"),
    path('profile/delete_image/<image_id>', views.delete_image, name="delete_image"),
    path('login', auth_views.LoginView.as_view(), name="login"),
    path('logout', views.log_out, name="logout"),
    path('change-password', auth_views.PasswordChangeView.as_view(success_url='change-password-done'), name='change'
                                                                                                            '_password'),
    path('change-password-done', auth_views.PasswordChangeDoneView.as_view(), name='change_password_done'),
    # reset password
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/blog/password'
                                                                                                     '-reset/complete'), name="password_reset_confirm"),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('register/', views.register, name='register'),
    path('register/edit', views.edit_account, name='edit_account'),
    path('profile/user', views.user, name='user'),
    path('profile/post_comment/<post_id>', views.post_comment_user, name='post_comment_user')
]

blogapp/models.py
import django.contrib.auth
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from django.forms import Form
from django_resized import ResizedImageField
import os
import shutil
from django.template.defaultfilters import slugify


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DA', 'Draft'
        PUBLISHED = 'PU', 'Published'
        REJECTED = 'RJ', 'Rejected'

    CATEGORY_CHOICES = (
        ('PL', 'Programming Language'),
        ('BC', 'Block Chain'),
        ('TL', 'Technology'),
        ('OT', 'Other')
    )
    # relations
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_posts')

    # data
    title = models.CharField(max_length=250)
    description = models.TextField(max_length=250)
    slug = models.SlugField(max_length=100)
    # date
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES, default='Other')

    reading_time = models.PositiveIntegerField(default=None)

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish'])]

    object = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:posts_detail', args=[self.id])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        for img in self.images.all():
            storage, path = img.image_file.storage, img.image_file.path
            storage.delete(path)
        super().delete(*args, **kwargs)


class Ticket(models.Model):
    name = models.CharField(max_length=25)
    message = models.TextField(max_length=250)
    phone = models.CharField(max_length=11)
    email = models.EmailField()
    subject = models.CharField(max_length=100)

    def __str__(self):
        return self.subject


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=250)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self):
        return f"{self.name}: {self.post}"


class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="images")
    image_file = ResizedImageField(upload_to="post_images/", size=[600, 400], quality=100, crop=['middle', 'center'])
    title = models.CharField(max_length=40)
    description = models.TextField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def delete(self, *args, **kwargs):
        storage, path = self.image_file.storage, self.image_file.path
        storage.delete(path)
        super().delete(*args, **kwargs)


class Account(models.Model):
    user = models.OneToOneField(User, related_name="account", on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, null=True)
    bio = models.TextField(max_length=200, blank=True, null=True)
    photo = ResizedImageField(upload_to="account_images/", size=[500, 500], quality=100, crop=['middle', 'center'],
                              blank=True, null=True)
    job = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.user.username

blogapp/forms.py
from django import forms
from .models import *


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ("Report", "Report"),
        ("Problem", "Problem"),
        ("Advice", "Advice"),
    )

    message = forms.CharField(
        widget=forms.Textarea and forms.TextInput(attrs={'placeholder': 'Massage', 'class': 'ticketmassage'}),
        required=True, )
    name = forms.CharField(max_length=250, required=True, widget=forms.TextInput(attrs={'placeholder': 'Name'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))
    phone = forms.CharField(max_length=11, required=True, widget=forms.NumberInput(attrs={'placeholder': 'Phone'}))
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError('Error:Number isnt valid!!! ')
            else:
                return phone


class CommentForm(forms.ModelForm):
    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError("name is short!!!")
            else:
                return name

    class Meta:

        model = Comment
        fields = ['name', 'body']
        widgets = {
            'body': forms.TextInput(attrs={
                'placeholder': 'body',
                'class': 'cm-body'
            }),
            'name': forms.TextInput(attrs={
                'placeholder': 'name',
                'class': 'cm-name'
            })
        }


class SearchForm(forms.Form):
    query = forms.CharField()


class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField()
    image2 = forms.ImageField()

    class Meta:
        model = Post
        fields = ['title', 'description', 'category', 'reading_time']


class UserRigesterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(), label='password')
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput(), label='repeat password')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('passwords do not match !')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['date_of_birth', 'bio', 'job', 'photo']

blogapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import *
from .forms import *
import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import DetailView, ListView
from django.views.decorators.http import require_POST
from django.db.models import Q
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery, TrigramSimilarity
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView


# Create your views here.
def index(reqeust):
    return render(reqeust, "blog/index.html")


def post_list(reqeust, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:

        posts = Post.published.all()
    paginator = Paginator(posts, 3)
    page_number = reqeust.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {
        'posts': posts,
    }
    return render(reqeust, "blog/list.html", context)


def posts_details(reqeust, id):
    post = get_object_or_404(Post, id=id, status=Post.Status.PUBLISHED)

    comments = post.comments.filter(active=True)
    form = CommentForm()
    context = {
        'post': post,
        'time': datetime.datetime.now(),
        'comments': comments
    }
    return render(reqeust, "blog/detail.html", context)


@login_required
def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket_obj = Ticket.objects.create()
            cd = form.cleaned_data
            ticket_obj.message = cd['message']
            ticket_obj.name = cd['name']
            ticket_obj.email = cd['email']
            ticket_obj.phone = cd['phone']
            ticket_obj.subject = cd['subject']
            ticket_obj.save()
            return redirect("blog:index")
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment
    }
    return render(request, "forms/comment.html", context)


def post_search(request):
    query = None
    result = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            result1 = Post.published.annotate(similarity=TrigramSimilarity('title', query)). \
                filter(similarity__gt=0.1)

            result2 = Post.published.annotate(similarity=TrigramSimilarity('description', query)). \
                filter(similarity__gt=0.1)
            result3 = Image.objects.annotate(similarity=TrigramSimilarity('description', query)). \
                filter(similarity__gt=0.1)

            result4 = Image.objects.annotate(similarity=TrigramSimilarity('title', query)). \
                filter(similarity__gt=0.1)

            result = (result1 | result2).order_by('-similarity')
            result_img = (result3 | result4).order_by('-similarity')

            context = {
                'query': query,
                'result': result,
                'result_img': result_img
            }

    return render(request, 'blog/search.html', context)


@login_required
def profile(request):
    post_pag = Post.published.all()
    user = request.user
    posts = Post.published.filter(author=user)
    paginator = Paginator(posts, 1)
    page_number = request.GET.get('page', 3)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    print(post_pag)
    context = {
        'posts': posts,
        'post_pag': post_pag
    }

    return render(request, 'blog/profile.html', context)


@login_required
def create_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create-post.html', {'form': form})


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        post.delete()
        return redirect("blog:profile")
    return render(request, 'forms/delete-post.html', {'post': post})


@login_required
def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect('blog:profile')


@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = CreatePostForm(instance=post)
    return render(request, 'forms/create-post.html', {'form': form, 'post': post})


def log_out(request):
    logout(request)
    return redirect(request.META.get('HTTP_REFERER'))


def register(request):
    if request.method == 'POST':
        form = UserRigesterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            Account.objects.create(
                user=user)
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRigesterForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def edit_account(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        account_form = AccountEditForm(request.POST, instance=request.user.account, files=request.FILES)
        if account_form.is_valid() and user_form.is_valid():
            account_form.save()
            user_form.save()
            return redirect('blog:profile')
    else:
        user_form = UserEditForm(instance=request.user)
        account_form = AccountEditForm(instance=request.user.account)
    context = {
        'account_form': account_form,
        'user_form': user_form
    }
    return render(request, 'registration/edit_account.html', context)

def user(request):
    print(request.user.id)
    user = Account.objects.filter(user_id=request.user.id)
    post = Image.objects.filter(post__author_id=request.user.id)
    context = {
        'user': user,
        'post': post
    }

    return render(request, 'blog/user.html', context)


def post_comment_user(request, post_id):
    post = Comment.objects.filter(post_id=post_id, active=True)
    print(post)
    return render(request, 'blog/post-comment.html', {'post': post})

blogapp/templates/blog/detail.html
{% extends 'parents/base.html' %}
{% load blog_tags %}

{%block title %} Detail_post{% endblock %}
{%block content%}

    <h2> Detail post </h2>
       <h1 class="post-detail" >{{ post.title}}</h1>
    <p class="author">author: {{ post.author }}</p>
    <span class="pub-date">{{ post.publish }}</span>
    <div>
        {% for img in post.images.all %}
            <img  width="400px"  height="350px" src="{{img.image_file.url }}" alt="{{ img.title }}">
            
        {% endfor %}
    <hr>
    </div>
    <div class="des">
    <p class="des-p">{{ post.description | cansor | markdown }}</p>
    </div>
    <hr>

    {{ time|date:"SHORT_DATETIME_FORMAT" }}
    <br>

    <div>
    {% with comments.count as cm_count%}
    {{ cm_count }} comment{{ cm_count|pluralize }}
    </div>

     <div>
     {% for cm in comments %}
         {{ cm.name |cansor }}:{{ cm.body|cansor |linebreaks }}

     {% empty %}
         No comment !
     {% endfor %}
     </div>
    {% endwith %}
    <form method="post" action="{% url 'blog:post_comment' post.id %}">
        {% csrf_token %}
        {{ form.as_ul }}
        <input type="submit" value="Add Comment">
    </form>
{% endblock %}

blogapp/templates/blog/index.html
{% extends 'parents/base.html' %}
{% load blog_tags %}
{% block title %}post list{% endblock %}
{% block content %}
    <h3>Static:</h3>
    <p>Number of post: {% total_posts %} </p>
    <p>Number  Comment: {% total_comments %}</p>
    <p>Date the last post: {% last_post_date %} </p>
    <h3>Post with the long reading time:</h3>{% longest_reading_time %}
    <h3>Post with the short reading time:</h3>{% shortest_reading_time %}
    {% latest_posts %}

    <h3>The most active Users: </h3><p>{% popular_user %}</p>

    {% random_post %}



{% endblock %}

blogapp/templates/blog/list.html
{% extends 'parents/base.html' %}
{% load blog_tags %}
{% block title %}post list{% endblock %}
{% block content %}

<h1 class="post-list">post list</h1>

<ol style="--length: {{ posts|length }}" role="list">
    {% for post in posts %}
        <li style="--i: {{ forloop.counter }}">
        <h3 class="post-title">
        <a href="{{post.get_absolute_url}}">{{ post.title }}</a>
        </h3>
        <p class="descr"> {{ post.description | truncatewords:4 |cansor }}</p>
        <img src="{{ post.images.first.image_file.url }}" alt="{{ post.images.first.title }}">
        </li>
    {% endfor %}
</ol>
    {% if category %}
        <h4><a href="{% url 'blog:post_list' %}" >posts list of {{ category }}</a></h4>
    {% else %}
        <h4><a href="{% url 'blog:post_list' %}" >post list</a></h4>
    {% endif %}
    <h3>Categories:</h3>
    <h4><a href="{% url 'blog:post_list_category' 'PL' %}">Programmin Language</a></h4>
    <h4><a href="{% url 'blog:post_list_category' 'BC' %}">Block Chain</a></h4>
    <h4><a href="{% url 'blog:post_list_category' 'TL' %}">Technology</a></h4>
    <h4><a href="{% url 'blog:post_list_category' 'OT' %}">Other</a></h4>



    {% include "partials/pagination.html" with page=posts %}

{% endblock %}

blogapp/templates/blog/post-comment.html
{% load blog_tags %}
<title>post_comment</title>
    <table style="width: 40%; text-align: left;">
           <tr>
           <th>Row</th>
           <th>User name</th>
           <th>Comment</th>
           </tr>
           {% for posts in post %}
               <tr>
               <td>{{ forloop.counter }}</td>
               <td>{{ posts.name }}</td>
               <td>{{ posts.body |cansor | truncatewords_html:2 }}</td>
               </tr>
            {% endfor %}
</table>

blogapp/templates/blog/profile.html
{% extends 'parents/base.html' %}
{% load blog_tags %}
{% block title %}profile{% endblock %}
{% block content %}
        <p><a href="{% url 'blog:create_post' %}">create post</a></p> <a href="{% url 'blog:user' %}">user information</a>
    <hr>
    <table style="width: 40%; text-align: left;">
           <tr>
           <th>Row</th>
           <th>Post</th>
           <th>Comment</th>
           <th>Edit</th>
           <th>Delete </th>
           </tr>
           {% for post in posts %}
               <tr>
               <td>{{ forloop.counter }}</td>
               <td><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></td>
               <td><a href="{% url 'blog:post_comment_user' post.id %}">comment</a></td>
               <td><a href="{% url 'blog:edit_post' post.id %}">Edit</a></td>
               <td><a href=" {% url "blog:delete_post" post.id  %}">Delete</a></td>


               </tr>
            {% endfor %}
</table>
    <hr>
    <a href=" {% url 'blog:edit_account' %} ">Edit account</a>
    <br>
    <hr>
    <a href=" {% url 'blog:change_password' %} ">Change password</a>
    <hr>
    <a href="{% url 'blog:logout' %}">Exit</a>

    {% include "partials/pagination.html" with page=posts %}
{% endblock %}

blogapp/templates/blog/search.html
{% extends 'parents/base.html' %}
{% block title %} Search Post{%  endblock %}
{% block content %}
    {% if query %}
        Result for {{ query }} is : {{ result.count }} in posts
    {% endif %}
    <br>
    {% for post in result %}
        <a href="{{  post.get_absolute_url}}"> {{ post.title }} </a>
        <p>{{ post.description | truncatewords:4  }}</p>
        <hr>lk
        {% empty %}
        <p>Not Result!!!</p>
    {% endfor %}

<hr>
<hr>


    {% if query %}
        Result for {{ query }} is : {{ result_img.count }} in images
    {% endif %}
    <br>
    {% for post in result_img %}
        <a href="{{  post.get_absolute_url}}"> {{ post.title }} </a>
        <p>{{ post.description | truncatewords:4  }}</p>
        <hr>
    {% empty %}
       <p>Not Result!!!</p>
    {% endfor %}



{% endblock %}

blogapp/templates/blog/user.html
<title>user</title>
    <p>first_name :{{ request.user.first_name }}</p><img  width="70px"  height="90px" src="{{request.user.account.photo.url}}" alt="{{ request.user.first_name }}">
    <hr>
    <p>last_name :{{ request.user.last_name }}</p>
    <hr>
    <p>Date of birth :{{ request.user.account.date_of_birth }}</p>
    <hr>
    <p>Bio :{{ request.user.account.bio }}</p>
    <hr>
    <p>Job :{{ request.user.account.job }}</p>
    <hr>
    <h4>post from user:</h4>
    {% for img in post %}
        <P><img  width="400px"  height="350px" src="{{img.image_file.url }}" alt="{{ img.title }}"></P>
        <BR>
    {% endfor %}